# Generated by Django 4.1.4 on 2023-01-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='file/', verbose_name='Image'),
        ),
    ]
